### ISSUE TITLE
modifier hidden ?

### ISSUE THREAD

**Issue by magsout** [cssrecipes/utils#10]
Something like `.r-*--hidden`   ?

**Comment by MoOx** [comment]
+1

**Comment by MoOx** [comment]
+ visible maybe ?

**Comment by bloodyowl** [comment]
visible would require us to handle any possible `display` value.

**Comment by bloodyowl** [comment]
also, it's already in the master https://github.com/cssrecipes/utils/blob/master/lib/sizes/all.css#L124-L130

**Comment by magsout** [comment]
![dr -who](https://cloud.githubusercontent.com/assets/1997108/7512778/9b3a9406-f4af-11e4-95fa-76bff6a0d1a6.gif)

**Comment by MoOx** [comment]
laul

**Comment by magsout** [comment]
`"cssrecipes-utils": "0.4.3",` in my package.json :(

pfffff
